name: deploy to dev env

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Generate session name
        id: session
        run: |
          repo="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          echo "name=${repo}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> "${GITHUB_OUTPUT}"

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.DEV_IAM_ROLE_ARN }}
          role-session-name: ${{ steps.session.outputs.name }}

      - name: Output step summary
        env:
          SESSION_NAME: ${{ steps.session.outputs.name }}
          CLOUDTRAIL_URL: https://console.aws.amazon.com/cloudtrail/home#/events
        run: |
          echo "## Authorized on AWS" >> "${GITHUB_STEP_SUMMARY}"
          echo "- ${CLOUDTRAIL_URL}?Username=${SESSION_NAME}" >> "${GITHUB_STEP_SUMMARY}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Export requirements.txt
        run: |
          uv export -o src/requirements.txt --no-hashes

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build & Deploy
        run: |
          sam build
          sam deploy --s3-bucket ${{secrets.DEV_S3_BUCKET}} --no-confirm-changeset
