name: PR Validation

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: |
          uv sync

      - name: Run ruff linter
        run: uvx ruff check

      - name: Run formatter
        run: uvx ruff format --check

  trivy-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Export requirements.txt
        run: uv export -o src/requirements.txt --no-hashes

      - name: Run Trivy vulnerability scanner for Python code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './src/'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  trivy-sam-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner for CloudFormation
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './template.yaml'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          include-non-failures: true
